[package]
name = "icmp-socket2"
description = "ICMP sockets for both IPv4 and IPv6. Fork of icmp-socket"
version = "0.6.0"
repository = "https://github.com/Lochnair/icmp-socket2"
authors = [
    "Jeremy Wall <jeremy@marzhillstudios.com>",
    "Nils Andreas Svee <me@lochnair.net>",
]
edition = "2024"
license = "Apache-2.0"

[dependencies.socket2]
version = "0.6"
features = ["all"]

[dependencies.async-io]
version = "2.6.0"
optional = true

[dependencies.futures-lite]
version = "2.6.1"
optional = true

[dependencies.async-trait]
version = "0.1.91"
optional = true

[dependencies.tokio]
version = "1.53.1"
default-features = false
features = ["rt", "net", "time"]
optional = true

[features]
default = []
async-io = [
    "dep:async-io",
    "dep:futures-lite",
    "dep:async-trait",
]
smol = ["async-io"]
tokio = [
    "dep:tokio",
    "dep:async-trait",
]

[[example]]
name = "async_ping4"
required-features = ["async-io"]

[[example]]
name = "tokio_ping4"
required-features = ["tokio"]
